# render.yaml
# This file defines your service for Render.
# It tells Render how to build and run your application, including system dependencies.

services:
  # A name for your service
  - name: gbp-analyzer-api
    # The type of service. 'web' for a web server.
    type: web
    # The runtime environment.
    env: python
    # This specifies the branch to deploy from.
    branch: feat/optimization
    # List of system-level packages to install using apt-get before the build starts.
    # This is the list of dependencies required by Playwright/Chromium.
    build:
      packages:
        - libnss3
        - libnspr4
        - libdbus-1-3
        - libatk1.0-0
        - libatk-bridge2.0-0
        - libcups2
        - libdrm2
        - libxkbcommon0
        - libxcomposite1
        - libxdamage1
        - libxfixes3
        - libxrandr2
        - libgbm1
        - libpango-1.0-0
        - libcairo2
        - libasound2
    # The command to build your application.
    # Note: We now use playwright install chromium WITHOUT --with-deps.
    buildCommand: "./build.sh"
    # The command to start your application.
    startCommand: "poetry run uvicorn src.main:app --host 0.0.0.0 --port $PORT"
